const LOGGED_IN = "LOGGED_IN";
const LOGGED_OUT = "LOGGED_OUT";
const ALL_POSTS = "ALL_POSTS";
const USER_PROFILE = "USER_PROFILE";
const POST_TAGS = "POST_TAGS";
const SEARCH_MOVIE = "SEARCH_MOVIE";
const MOVIES = "MOVIES";
const SINGLE_MOVIE = "SINGLE_MOVIE";

export {
	LOGGED_IN,
	LOGGED_OUT,
	ALL_POSTS,
	USER_PROFILE,
	POST_TAGS,
	SEARCH_MOVIE,
	MOVIES,
	SINGLE_MOVIE,
};
